### ISSUE TITLE
AttributeError: module 'igl' has no attribute 'eigen'

### ISSUE THREAD

**Issue by dypromise** [AndyLiming/CSDNet-2021#2]
Hi, When I install igl with conda, I encountered an error: "AttributeError: module 'igl' has no attribute 'eigen'", could you tell me what the igl's version and how did you installed it. thank you

**Comment by AndyLiming** [comment]
Hi, I use the libigl-python-bindings (https://github.com/libigl/libigl-python-bindings) the version is 2.2.1. According to the documents of libigl, the recommended way to install is to run "conda install -c conda-forge igl". While I installed libigl by downloading the release package and running setup.py.  
libigl is only required by the generation of mesh files. If you have problems with the libigl installation, you can also download the mesh files directly from this link https://drive.google.com/file/d/1TgO4mSmRFXLr5WR8uH31m4fgCvrqYpKd/view?usp=share_link. 
Or you can find more information in the repo of meshcnn: https://github.com/maxjiang93/ugscnn.
Thank you!
